2021-01-31 12:34:22.1404|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2021-01-31 12:34:22.4624|ERROR|SampleProject.Controllers.ErrorController|The Path /Home/Details/1 throw as exception System.Exception: Error in Details View
   at SampleProject.Controllers.HomeController.Details(Nullable`1 id) in D:\cSharp\Core\DotNet-Core\SampleProject\Controllers\HomeController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2021-01-31 12:45:49.1965|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2021-01-31 12:45:49.2904|ERROR|SampleProject.Controllers.ErrorController|The Path /Home/Details/33 throw as exception System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'SampleProject.Controllers.HomeController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2021-01-31 12:46:20.6370|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2021-01-31 12:46:20.6370|ERROR|SampleProject.Controllers.ErrorController|The Path / throw as exception System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'SampleProject.Controllers.HomeController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2021-01-31 12:48:02.9662|TRACE|SampleProject.Controllers.HomeController|Trace Log
2021-01-31 12:48:03.0916|DEBUG|SampleProject.Controllers.HomeController|Debug Log
2021-01-31 12:48:03.0964|INFO|SampleProject.Controllers.HomeController|Information Log
2021-01-31 12:48:03.1229|WARN|SampleProject.Controllers.HomeController|Warning Log
2021-01-31 12:48:03.1229|ERROR|SampleProject.Controllers.HomeController|Error Log
2021-01-31 12:48:03.1303|FATAL|SampleProject.Controllers.HomeController|Critical Log
2021-01-31 12:50:57.5217|TRACE|SampleProject.Controllers.HomeController|Trace Log
2021-01-31 12:50:57.6560|DEBUG|SampleProject.Controllers.HomeController|Debug Log
2021-01-31 12:50:57.6666|INFO|SampleProject.Controllers.HomeController|Information Log
2021-01-31 12:50:57.7026|WARN|SampleProject.Controllers.HomeController|Warning Log
2021-01-31 12:50:57.7113|ERROR|SampleProject.Controllers.HomeController|Error Log
2021-01-31 12:50:57.7113|FATAL|SampleProject.Controllers.HomeController|Critical Log
2021-01-31 12:50:57.7314|TRACE|SampleProject.Models.SqlEmplyeeRepository|Trace Log
2021-01-31 12:50:57.7395|DEBUG|SampleProject.Models.SqlEmplyeeRepository|Debug Log
2021-01-31 12:50:57.7395|INFO|SampleProject.Models.SqlEmplyeeRepository|Information Log
2021-01-31 12:50:57.7620|WARN|SampleProject.Models.SqlEmplyeeRepository|Warning Log
2021-01-31 12:50:57.7731|ERROR|SampleProject.Models.SqlEmplyeeRepository|Error Log
2021-01-31 12:50:57.7848|FATAL|SampleProject.Models.SqlEmplyeeRepository|Critical Log
2021-01-31 12:55:13.9947|WARN|SampleProject.Controllers.HomeController|Warning Log
2021-01-31 12:55:14.0799|ERROR|SampleProject.Controllers.HomeController|Error Log
2021-01-31 12:55:14.0896|FATAL|SampleProject.Controllers.HomeController|Critical Log
2021-01-31 12:55:14.0965|TRACE|SampleProject.Models.SqlEmplyeeRepository|Trace Log
2021-01-31 12:55:14.0965|DEBUG|SampleProject.Models.SqlEmplyeeRepository|Debug Log
2021-01-31 12:55:14.0965|INFO|SampleProject.Models.SqlEmplyeeRepository|Information Log
2021-01-31 12:55:14.1149|WARN|SampleProject.Models.SqlEmplyeeRepository|Warning Log
2021-01-31 12:55:14.1149|ERROR|SampleProject.Models.SqlEmplyeeRepository|Error Log
2021-01-31 12:55:14.1311|FATAL|SampleProject.Models.SqlEmplyeeRepository|Critical Log
